
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:233 (message)"
      - "CMakeLists.txt:3 (project)"
    message: |
      The system is: Windows - 10.0.22621 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      MSBuild version 17.4.0+18d5aef85 for .NET Framework
      Compilação de 02/12/2023 18:00:10 iniciada.
      Projeto "C:\\Users\\guidp\\programming\\projects\\Iterated-Local-Search\\build_windows\\CMakeFiles\\3.28.0-rc5\\CompilerIdC\\CompilerIdC.vcxproj" no nó 1 (destinos padrão).
      PrepareForBuild:
        Criando o diretório "Debug\\".
        Criando o diretório "Debug\\CompilerIdC.tlog\\".
      InitializeBuildStatus:
        Criando "Debug\\CompilerIdC.tlog\\unsuccessfulbuild" porque "AlwaysCreate" foi especificado.
      ClCompile:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TC /FC /errorReport:queue CMakeCCompilerId.c
        CMakeCCompilerId.c
      Link:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdC.lib" /MACHINE:X64 Debug\\CMakeCCompilerId.obj
        CompilerIdC.vcxproj -> C:\\Users\\guidp\\programming\\projects\\Iterated-Local-Search\\build_windows\\CMakeFiles\\3.28.0-rc5\\CompilerIdC\\CompilerIdC.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_C_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_C_COMPILER=C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.34.31933\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        Excluindo o arquivo "Debug\\CompilerIdC.tlog\\unsuccessfulbuild".
        Tocando "Debug\\CompilerIdC.tlog\\CompilerIdC.lastbuildstate".
      Projeto de compilação pronto "C:\\Users\\guidp\\programming\\projects\\Iterated-Local-Search\\build_windows\\CMakeFiles\\3.28.0-rc5\\CompilerIdC\\CompilerIdC.vcxproj" (destinos padrão).
      
      Compilação com êxito.
          0 Aviso(s)
          0 Erro(s)
      
      Tempo Decorrido 00:00:01.33
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"
      
      The C compiler identification is MSVC, found in:
        C:/Users/guidp/programming/projects/Iterated-Local-Search/build_windows/CMakeFiles/3.28.0-rc5/CompilerIdC/CompilerIdC.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      MSBuild version 17.4.0+18d5aef85 for .NET Framework
      Compilação de 02/12/2023 18:00:12 iniciada.
      Projeto "C:\\Users\\guidp\\programming\\projects\\Iterated-Local-Search\\build_windows\\CMakeFiles\\3.28.0-rc5\\CompilerIdCXX\\CompilerIdCXX.vcxproj" no nó 1 (destinos padrão).
      PrepareForBuild:
        Criando o diretório "Debug\\".
        Criando o diretório "Debug\\CompilerIdCXX.tlog\\".
      InitializeBuildStatus:
        Criando "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild" porque "AlwaysCreate" foi especificado.
      ClCompile:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TP /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X64 Debug\\CMakeCXXCompilerId.obj
        CompilerIdCXX.vcxproj -> C:\\Users\\guidp\\programming\\projects\\Iterated-Local-Search\\build_windows\\CMakeFiles\\3.28.0-rc5\\CompilerIdCXX\\CompilerIdCXX.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_CXX_COMPILER=C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.34.31933\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        Excluindo o arquivo "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild".
        Tocando "Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.lastbuildstate".
      Projeto de compilação pronto "C:\\Users\\guidp\\programming\\projects\\Iterated-Local-Search\\build_windows\\CMakeFiles\\3.28.0-rc5\\CompilerIdCXX\\CompilerIdCXX.vcxproj" (destinos padrão).
      
      Compilação com êxito.
          0 Aviso(s)
          0 Erro(s)
      
      Tempo Decorrido 00:00:00.93
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"
      
      The CXX compiler identification is MSVC, found in:
        C:/Users/guidp/programming/projects/Iterated-Local-Search/build_windows/CMakeFiles/3.28.0-rc5/CompilerIdCXX/CompilerIdCXX.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:3 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "C:/Users/guidp/programming/projects/Iterated-Local-Search/build_windows/CMakeFiles/CMakeScratch/TryCompile-j8a6p1"
      binary: "C:/Users/guidp/programming/projects/Iterated-Local-Search/build_windows/CMakeFiles/CMakeScratch/TryCompile-j8a6p1"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS /W3"
      CMAKE_C_FLAGS_DEBUG: "/MDd /Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/guidp/programming/projects/Iterated-Local-Search/build_windows/CMakeFiles/CMakeScratch/TryCompile-j8a6p1'
        
        Run Build Command(s): "C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_f0152.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        MSBuild version 17.4.0+18d5aef85 for .NET Framework
        Compilação de 02/12/2023 18:00:14 iniciada.
        Projeto "C:\\Users\\guidp\\programming\\projects\\Iterated-Local-Search\\build_windows\\CMakeFiles\\CMakeScratch\\TryCompile-j8a6p1\\cmTC_f0152.vcxproj" no nó 1 (destinos padrão).
        PrepareForBuild:
          Criando o diretório "cmTC_f0152.dir\\Debug\\".
          Criando o diretório "C:\\Users\\guidp\\programming\\projects\\Iterated-Local-Search\\build_windows\\CMakeFiles\\CMakeScratch\\TryCompile-j8a6p1\\Debug\\".
          Criando o diretório "cmTC_f0152.dir\\Debug\\cmTC_f0152.tlog\\".
        InitializeBuildStatus:
          Criando "cmTC_f0152.dir\\Debug\\cmTC_f0152.tlog\\unsuccessfulbuild" porque "AlwaysCreate" foi especificado.
        ClCompile:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX64\\x64\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_f0152.dir\\Debug\\\\" /Fd"cmTC_f0152.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TC /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.28\\Modules\\CMakeCCompilerABI.c"
          Microsoft (R) C/C++ Optimizing Compiler Versão 19.34.31935 para x64
          CMakeCCompilerABI.c
          Copyright (C) Microsoft Corporation. Todos os direitos reservados.
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_f0152.dir\\Debug\\\\" /Fd"cmTC_f0152.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TC /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.28\\Modules\\CMakeCCompilerABI.c"
        Link:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\Users\\guidp\\programming\\projects\\Iterated-Local-Search\\build_windows\\CMakeFiles\\CMakeScratch\\TryCompile-j8a6p1\\Debug\\cmTC_f0152.exe" /INCREMENTAL /ILK:"cmTC_f0152.dir\\Debug\\cmTC_f0152.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/Users/guidp/programming/projects/Iterated-Local-Search/build_windows/CMakeFiles/CMakeScratch/TryCompile-j8a6p1/Debug/cmTC_f0152.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Users/guidp/programming/projects/Iterated-Local-Search/build_windows/CMakeFiles/CMakeScratch/TryCompile-j8a6p1/Debug/cmTC_f0152.lib" /MACHINE:X64  /machine:x64 cmTC_f0152.dir\\Debug\\CMakeCCompilerABI.obj
          cmTC_f0152.vcxproj -> C:\\Users\\guidp\\programming\\projects\\Iterated-Local-Search\\build_windows\\CMakeFiles\\CMakeScratch\\TryCompile-j8a6p1\\Debug\\cmTC_f0152.exe
        FinalizeBuildStatus:
          Excluindo o arquivo "cmTC_f0152.dir\\Debug\\cmTC_f0152.tlog\\unsuccessfulbuild".
          Tocando "cmTC_f0152.dir\\Debug\\cmTC_f0152.tlog\\cmTC_f0152.lastbuildstate".
        Projeto de compilação pronto "C:\\Users\\guidp\\programming\\projects\\Iterated-Local-Search\\build_windows\\CMakeFiles\\CMakeScratch\\TryCompile-j8a6p1\\cmTC_f0152.vcxproj" (destinos padrão).
        
        Compilação com êxito.
            0 Aviso(s)
            0 Erro(s)
        
        Tempo Decorrido 00:00:01.12
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:3 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "C:/Users/guidp/programming/projects/Iterated-Local-Search/build_windows/CMakeFiles/CMakeScratch/TryCompile-hz18f2"
      binary: "C:/Users/guidp/programming/projects/Iterated-Local-Search/build_windows/CMakeFiles/CMakeScratch/TryCompile-hz18f2"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /W3 /GR /EHsc"
      CMAKE_CXX_FLAGS_DEBUG: "/MDd /Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/guidp/programming/projects/Iterated-Local-Search/build_windows/CMakeFiles/CMakeScratch/TryCompile-hz18f2'
        
        Run Build Command(s): "C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_6d2d7.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        MSBuild version 17.4.0+18d5aef85 for .NET Framework
        Compilação de 02/12/2023 18:00:16 iniciada.
        Projeto "C:\\Users\\guidp\\programming\\projects\\Iterated-Local-Search\\build_windows\\CMakeFiles\\CMakeScratch\\TryCompile-hz18f2\\cmTC_6d2d7.vcxproj" no nó 1 (destinos padrão).
        PrepareForBuild:
          Criando o diretório "cmTC_6d2d7.dir\\Debug\\".
          Criando o diretório "C:\\Users\\guidp\\programming\\projects\\Iterated-Local-Search\\build_windows\\CMakeFiles\\CMakeScratch\\TryCompile-hz18f2\\Debug\\".
          Criando o diretório "cmTC_6d2d7.dir\\Debug\\cmTC_6d2d7.tlog\\".
        InitializeBuildStatus:
          Criando "cmTC_6d2d7.dir\\Debug\\cmTC_6d2d7.tlog\\unsuccessfulbuild" porque "AlwaysCreate" foi especificado.
        ClCompile:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX64\\x64\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_6d2d7.dir\\Debug\\\\" /Fd"cmTC_6d2d7.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TP /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.28\\Modules\\CMakeCXXCompilerABI.cpp"
          Microsoft (R) C/C++ Optimizing Compiler Versão 19.34.31935 para x64
          CMakeCXXCompilerABI.cpp
          Copyright (C) Microsoft Corporation. Todos os direitos reservados.
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_6d2d7.dir\\Debug\\\\" /Fd"cmTC_6d2d7.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TP /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.28\\Modules\\CMakeCXXCompilerABI.cpp"
        Link:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\Users\\guidp\\programming\\projects\\Iterated-Local-Search\\build_windows\\CMakeFiles\\CMakeScratch\\TryCompile-hz18f2\\Debug\\cmTC_6d2d7.exe" /INCREMENTAL /ILK:"cmTC_6d2d7.dir\\Debug\\cmTC_6d2d7.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/Users/guidp/programming/projects/Iterated-Local-Search/build_windows/CMakeFiles/CMakeScratch/TryCompile-hz18f2/Debug/cmTC_6d2d7.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Users/guidp/programming/projects/Iterated-Local-Search/build_windows/CMakeFiles/CMakeScratch/TryCompile-hz18f2/Debug/cmTC_6d2d7.lib" /MACHINE:X64  /machine:x64 cmTC_6d2d7.dir\\Debug\\CMakeCXXCompilerABI.obj
          cmTC_6d2d7.vcxproj -> C:\\Users\\guidp\\programming\\projects\\Iterated-Local-Search\\build_windows\\CMakeFiles\\CMakeScratch\\TryCompile-hz18f2\\Debug\\cmTC_6d2d7.exe
        FinalizeBuildStatus:
          Excluindo o arquivo "cmTC_6d2d7.dir\\Debug\\cmTC_6d2d7.tlog\\unsuccessfulbuild".
          Tocando "cmTC_6d2d7.dir\\Debug\\cmTC_6d2d7.tlog\\cmTC_6d2d7.lastbuildstate".
        Projeto de compilação pronto "C:\\Users\\guidp\\programming\\projects\\Iterated-Local-Search\\build_windows\\CMakeFiles\\CMakeScratch\\TryCompile-hz18f2\\cmTC_6d2d7.vcxproj" (destinos padrão).
        
        Compilação com êxito.
            0 Aviso(s)
            0 Erro(s)
        
        Tempo Decorrido 00:00:01.00
        
      exitCode: 0
...
